title: Toko Bunga Pontianak
description: Toko Bunga Pontianak Asry Florist 081396353338.
show_downloads: false

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://tokobungapontianak.github.io" # change this to the base hostname & protocol for your site


google_analytics: G-MQQ3HPW2BL

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: tokobungapontianak
image: /thumbnail-jumbo.png
twitter:
  username: AsryFlorist

plugins:
  - jekyll-target-blank
  - jekyll-figure
  - jekyll-loading-lazy
  - jekyll-feed
  - jekyll-sitemap

target-blank:
    rel: noopener

header_page_refs: ['now', 'about', 'contact']

disqus: 
  shortname: tokobungadibatam

include:
  - "image"
